In [1]:
import pandas as pd
import seaborn as sns

In [2]:
dataset = sns.load_dataset("titanic")
dataset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
dataset.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
dataset["age"] = dataset["age"].fillna(dataset["age"].mean())

In [8]:
data = dataset["sex"]
pd.get_dummies(data)

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
encoded = ohe.fit_transform(dataset[["sex"]])
encoded

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]], shape=(891, 2))

In [13]:
encoded_df = pd.DataFrame(encoded,columns = ohe.get_feature_names_out(['sex']))
encoded_df.head()

   sex_female  sex_male
0         0.0       1.0
1         1.0       0.0
2         1.0       0.0
3         1.0       0.0
4         0.0       1.0

In [15]:
pd.get_dummies(dataset,columns=["sex"])

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male
0,0,3,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True,False
2,1,3,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True,False
3,1,1,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True,False
4,0,3,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,False,True
887,1,1,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True,False
888,0,3,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True,False
889,1,1,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,False,True
890,0,3,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,False,True