# Train Test Split

In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("loan_approval_dataset.csv")
dataset.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [17]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   str
 3    self_employed             4269 non-null   str
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   str
dtypes: int64(10), str(3)
memory usage: 531.6 KB

In [18]:
dataset.shape

(4269, 13)

In [5]:
input_data = dataset.iloc[:,:-1]
output_data = dataset[" loan_status"]

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
x_train , x_test, y_train , y_test = train_test_split(input_data,output_data,test_size=0.25)

In [21]:
x_train.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
3997,3998,4,Graduate,No,6900000,16500000,8,426,3900000,5200000,18300000,9000000
3593,3594,2,Graduate,No,2200000,6800000,20,546,4600000,200000,4500000,2200000
336,337,3,Graduate,No,7900000,18300000,10,731,4200000,3400000,22200000,8400000
1797,1798,0,Not Graduate,Yes,8000000,21100000,6,306,16100000,11800000,28200000,8700000
1703,1704,5,Graduate,No,5400000,19700000,20,423,6500000,10000000,15700000,7300000

In [25]:
x_test.shape , y_test.shape

((1068, 12), (1068,))